
*******************************************
+ Name: weixiabing
+ Date: 9/14/22
********************************************


In [9]:
import h5py
import cupy as cp
import matplotlib.pyplot as plt
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
import  pandas as pd
import  os
from keras.models import Sequential, load_model
from sklearn.preprocessing import MinMaxScaler

In [10]:
#读取数据
f = h5py.File('D:\library\Github\Innovative-practice\library\csv\第三学期\data_git_version.h5', 'r')
data_o = f['data']
data_o = cp.array(data_o)
print(data_o.shape)
#数据换轴
data_o = cp.transpose(data_o,(1,0,2))
print(data_o.shape)
#数据降维
data=cp.reshape(data_o,(-1,3))
print(data.shape)

(1488, 10000, 3)
(10000, 1488, 3)
(14880000, 3)


In [11]:
#定义data_n为(n,5)的数组
data_n=cp.zeros((data.shape[0],5))
print(data_n.shape)
#将data中的数据复制到data_n中
data_n[:,2:5]=data
#date_n[:,0]赋值为0-1487重复10000次
data_n[:,1]=cp.repeat(cp.arange(0,10000),1488)
#date_n[:,0]赋值为0-1488循环10000次
data_n[:,0]=cp.tile(cp.arange(0,1488),10000)


(14880000, 5)


In [14]:
#data_n转化为(1488,10000,5)的数组
data_n=cp.reshape(data_n,(10000, 1488,5))
print(data_n.shape)


(10000, 1488, 5)


In [16]:
print(data_n[0,0:10,:])

[[0.0000e+00 0.0000e+00 3.1890e+00 1.0210e+00 5.7799e+01]
 [1.0000e+00 0.0000e+00 1.9340e+00 3.8500e-01 4.4047e+01]
 [2.0000e+00 0.0000e+00 7.1600e-01 1.6400e-01 4.1207e+01]
 [3.0000e+00 0.0000e+00 2.0480e+00 2.8000e-02 3.3022e+01]
 [4.0000e+00 0.0000e+00 8.6500e-01 3.1000e-02 3.1377e+01]
 [5.0000e+00 0.0000e+00 3.6200e-01 2.1200e-01 3.4842e+01]
 [6.0000e+00 0.0000e+00 3.3100e-01 3.7500e-01 3.5416e+01]
 [7.0000e+00 0.0000e+00 1.1240e+00 7.3800e-01 4.2934e+01]
 [8.0000e+00 0.0000e+00 5.1020e+00 2.4380e+00 5.9881e+01]
 [9.0000e+00 0.0000e+00 6.4750e+00 6.1330e+00 7.1136e+01]]


In [22]:
#生成100个（0，10000）的随机数
index=cp.random.randint(0,10000,5000)
print(index)
data_random=data_n[index,:,:]




[9085 5090 7299 6053 3508 6189 7548 7992 4827 4586 5080 6753 3658 5005
 9093 3475 9280 1771 3346 9968 6626 2739 4995 4449 4411 4468 1824 8952
 9041 3311 7016 1423 4608 4175 8861  620 1653 2131 3619 4191 7885 2053
 4748 6075 9069  104 2863 1425 1489 3758 3376 8971  387 4626 2637 5026
 5305 3043 3793 2163 7118 5442 4209 2210 6792 4398 3011 3033 7231 2725
 5742 2516 4883 1345 3705 8584 4131 4534  704 3891 8187 2513 1624 6179
 9343 5406 3297 8877 4592  874 2782 4202 8435 2685 8025 9304 4335 4823
 5215 8456]


In [26]:
train_size = int(1488* 0.8)
trainlist=data_random[:,0:train_size,:]
testlist=data_random[:,train_size:,:]
print(trainlist.shape)
print(testlist.shape)
#trainlist转化为二维
trainlist=cp.reshape(trainlist,(-1,5))
print(trainlist.shape)
#testlist转化为二维
testlist=cp.reshape(testlist,(-1,5))
print(testlist.shape)
#将trainlist和testlist转化为dataframe
trainlist=pd.DataFrame(trainlist.get(), columns=['time','place','sms','call','internet'])
testlist=pd.DataFrame(testlist.get(), columns=['time','place','sms','call','internet'])
#将trainlist和testlist转化为csv文件
trainlist.to_csv('D:\library\Github\Innovative-practice\library\csv\第三学期/trainlist.csv',index=False)
testlist.to_csv('D:\library\Github\Innovative-practice\library\csv\第三学期/testlist.csv',index=False)


(100, 1190, 5)
(100, 298, 5)
(119000, 5)
(29800, 5)
